### ISSUE TITLE
vue3 vite waterfall-item top 问题

### ISSUE THREAD

**Issue by akgitcom** [gk-shi/v3-waterfall#14]
"dependencies": {
    "v3-waterfall": "^1.1.3",
    "vue": "^3.2.45"
  },

waterfall-item top属性很小 ，上下两行都叠加了
没有改动
`
<template>
      <V3waterfall class="waterfall" :list="state.list" srcKey="cover" :gap="12" :colWidth="280"
                   :distanceToScroll="200" :isLoading="state.loading" :isOver="state.over" @scrollReachBottom="getNext">
        <template v-slot:default="slotProp">
          <div class="list-item">
            <a :href="'https://gkshi.com/blog/' + slotProp.item.id">
              <div class="cover-wrapper">
                <img v-if="slotProp.item.url" :src="slotProp.item.url" class="cover"/>
              </div>
              <div class="brief">
                
                <h3>{{ slotProp.item.name }}</h3>
                <p>{{ slotProp.item.name }}</p>
              </div>
            </a>
          </div>
        </template>
      </V3waterfall>
</template>
`

**Comment by devpage** [comment]
古德古德
