### ISSUE TITLE
在同一页面多次使用时样式错乱

### ISSUE THREAD

**Issue by LvHuaiSheng** [gk-shi/v3-waterfall#15]
### 需求：在同一页面使用tab标签展示不同类型数据，使用两个v3-waterfall组件展示不同数据时只有第一个组件渲染为正常使用，第二个tab组件渲染错乱如下图：
![图片](https://github.com/gk-shi/v3-waterfall/assets/35132878/4b641e90-66b9-43b7-9fef-0e5b099e2f2e)
#### 第一个默认展示的tab效果正常，如图：
![图片](https://github.com/gk-shi/v3-waterfall/assets/35132878/90433538-f8ad-444b-8fcb-b7ab41f696a7)

**Comment by gk-shi** [comment]
问题我已经大致知道是怎么触发的了，我会尽快进行版本修复。
基于你当前的问题，有个暂时的降级方案可以考虑，就是给 v3-waterfall 绑定一个 key，在切换 tab 的时候更新一下这个 key。
这样会触发重新渲染，应该可以临时解决。
最后，感谢你的使用反馈~

**Comment by Simpleddm** [comment]
同样碰到这个问题，请问这个问题有修复吗

**Comment by gk-shi** [comment]
@Simpleddm 你好，如果你也是需要在 tab 切换里需要展示不同数据的话，目前也是建议先使用一个 v3-warfall 组件，然后 tab 切换后把数据源更新掉。
目前还未修复该问题的原因：
由于当前版本触发加载的方式是监听滚动条，所以如果在一个页面挂载多个 v3-waterfall 的话，会有滚动穿越影响的问题；同时因为位置编排时只会找第一个 v3-waterfall 的容器来排布(这也是造成该 issue bug所在)。
换句话说，我设计之初考虑的就是一个页面就只存在一个 v3-waterfall.

当前在做：
目前我是准备将监听滚动换成`IntersectionObserver`方式来实现触底加载，这样就能通过透传 props 来控制挂载多个 v3-waterfall 时的独立监听。
因为我在尝试将排版做成数据响应式驱动的，而不是传统的  渲染->计算排版->绝对定位移动->显示  这么一个流程，目前是遇到了些困难点，还没很好地解决，因此就还没有发布出 2.0 版本...工作之余我会尽快解决(最近公司在赶项目进度╮(╯▽╰)╭)，实在不行我先切换回传统布局方式发布新版本。

对影响你们使用体验深感抱歉！

**Comment by Simpleddm** [comment]
> @Simpleddm 你好，如果你也是需要在 tab 切换里需要展示不同数据的话，目前也是建议先使用一个 v3-warfall 组件，然后 tab 切换后把数据源更新掉。 目前还未修复该问题的原因： 由于当前版本触发加载的方式是监听滚动条，所以如果在一个页面挂载多个 v3-waterfall 的话，会有滚动穿越影响的问题；同时因为位置编排时只会找第一个 v3-waterfall 的容器来排布(这也是造成该 issue bug所在)。 换句话说，我设计之初考虑的就是一个页面就只存在一个 v3-waterfall.
> 
> 当前在做： 目前我是准备将监听滚动换成`IntersectionObserver`方式来实现触底加载，这样就能通过透传 props 来控制挂载多个 v3-waterfall 时的独立监听。 因为我在尝试将排版做成数据响应式驱动的，而不是传统的 渲染->计算排版->绝对定位移动->显示 这么一个流程，目前是遇到了些困难点，还没很好地解决，因此就还没有发布出 2.0 版本...工作之余我会尽快解决(最近公司在赶项目进度╮(╯▽╰)╭)，实在不行我先切换回传统布局方式发布新版本。
> 
> 对影响你们使用体验深感抱歉！

感谢作者的分享，等待解决。。。

**Comment by gk-shi** [comment]
最新的响应式设计方案暂时还没空做好全面的测试，所以先优先解决该问题。该功能在最新版本`v1.2.1`中已经支持，但有些需要注意的地方：

<img width="751" alt="image" src="https://github.com/gk-shi/v3-waterfall/assets/27017919/b5f932e2-1824-4f9e-84a0-959a346303ee">

---
图片中划线的部分，需要各自维护自己的变量(当然，除非不得已，还是建议一个页面中只挂载一个 v3-waterfall 组件)。
赶在端午的最后一天完成，祝各位端午安康~
