### ISSUE TITLE
有考虑加上虚拟滚动吗？

### ISSUE THREAD

**Issue by dxhuii** [gk-shi/v3-waterfall#18]
支持page-mode,就是支持windows滚动
https://tangbc.github.io/vue-virtual-scroll-list/#/page-mode

数据量特别大，一直加载，DOM太多，会比较占用内存

**Comment by gk-shi** [comment]
近期比较忙，十一月中旬左右看一下

**Comment by gk-shi** [comment]
本次对虚拟列表的支持，稍有不同：
1.由于瀑布流需要预加载元素进行位置排版计算，且滚动时是做增量计算的，所以需要保持已展示数组的长度比较，并不是仅截取出当前位置需要显示的元素进行展示。
2.基于第 1 点说的问题，所以实际的虚拟列表表现为如下图：
![image](https://github.com/gk-shi/v3-waterfall/assets/27017919/5a614b0f-7c69-472b-ba80-0328b810e000)
对于超出显示范围的元素，会隐藏用户自己通过 slot 实现的内容，而会保留本组件内部用来实现排版的外壳(意思为被隐藏的元素不是全部影藏，而会留一个外层 div)。

组件默认不会开启虚拟列表，具体使用方法会在文档进行相关更新。
