### ISSUE TITLE
必须要包含图片内容？

### ISSUE THREAD

**Issue by Lingouzi** [gk-shi/v3-waterfall#2]
content 使用文字不可以么？

**Comment by gk-shi** [comment]
![image](https://user-images.githubusercontent.com/27017919/141278571-2c9cbb1a-0def-47a6-9bfb-660a71856b7d.png)
是指在例子中我箭头指向的这样嘛

**Comment by Lingouzi** [comment]
刚试了下，setup 返回的数据没有加载一直显示 loading，会是什么问题呢？
```
<v3-waterfall class="waterfall" :list="items" @scrollReachBottom="getList">
  <template #default="{item}">
    {{ item }}
  </template>
</v3-waterfall>


setup 部分代码：

const state = reactive({
  items: [],
})

function xx(){
  notes().then(res=>{
state.items = res.data
})

return {
        ...toRefs(state),
        getList
      }
}

```

**Comment by gk-shi** [comment]
@Lingouzi 我尝试在 `example/`的项目里按照你提供的代码片段的调用方式，依然是能够正常显示的。😂，如果方便的话，可以提供一个无法正常使用的最小项目 github 地址给我，我可以看下。

**Comment by Lingouzi** [comment]
https://gitee.com/linyun2018/test-waterfall.git
@gk-shi 基本上什么都没有的，这种使用方式是否正确？

**Comment by gk-shi** [comment]
@Lingouzi 感谢提供代码片段，是我的库的问题，没有兼容到 content 完全不含图片的情况，只兼容了其中某一项 item 不含图片的情况，会尽快修复。

**Comment by gk-shi** [comment]
@Lingouzi 你好，问题已修复，更新到 `1.1.2`版本即可，再次感谢提供帮助😁
