### ISSUE TITLE
vue3+ts 实现带搜索功能的瀑布流无法触发加载更多

### ISSUE THREAD

**Issue by wenzhihao123** [gk-shi/v3-waterfall#21]
vue3+ts 实现带搜索功能的瀑布流，初次进入不搜索可以正常滚动并加载更多，但是如果搜索加一个条件之后搜索出来不足一页的数据，然后清除条件加载出来的数据再滚动到底部无法触发加载更多，getNext方法不执行。代码就是参考的demo。

**Comment by wenzhihao123** [comment]
<img width="1486" alt="image" src="https://github.com/gk-shi/v3-waterfall/assets/9973952/b8a033d4-081b-4726-94e9-7a30403fdca4">

楼主这个酷炫的博客网站也有同样的问题，刚进入加载了全部的博客，选中vite之后，再选择全部，滑动到底部就不会加载更多了~

**Comment by gk-shi** [comment]
@wenzhihao123 会尽快修复~目前提供一个不太优雅的解决方案：在 `<v3-waterfall :key="forceUpdateKey">` 绑定一个 key，然后在切换标签(或者重新搜索的时候)，把`forceUpdateKey` 更新一个值，强制它重新弄渲染(注意，可能需要重置`isOver`绑定的值为 `false`)，应该可以达到效果。

**Comment by wenzhihao123** [comment]
> @wenzhihao123 会尽快修复~目前提供一个不太优雅的解决方案：在 `<v3-waterfall :key="forceUpdateKey">` 绑定一个 key，然后在切换标签(或者重新搜索的时候)，把`forceUpdateKey` 更新一个值，强制它重新弄渲染(注意，可能需要重置`isOver`绑定的值为 `false`)，应该可以达到效果。

感谢楼主的回复~ 这个方案我试了，页面数据不刷新，求大佬看下，非常感谢

**Comment by gk-shi** [comment]
@wenzhihao123 更新使用最新 1.3.1 版本即可，不需要额外的`key`来强制更新了

**Comment by wenzhihao123** [comment]
> @wenzhihao123 更新使用最新 1.3.1 版本即可，不需要额外的`key`来强制更新了

@gk-shi 已经使用最新 1.3.1 版本没啥问题了，谢谢大佬~
