### ISSUE TITLE
组件如果使用v-if问题

### ISSUE THREAD

**Issue by Yefancy** [gk-shi/v3-waterfall#23]
如果waterfall的组件及其父组件被v-if标记，第一次从false到true时没有问题，但是当true到false时报错。
使用v-show没问题。
但是希望动态生成 而不是总是渲染 避免过大的开销

**Comment by gk-shi** [comment]
不好意思，我没太理解是在哪种情况下出现的问题，我在：[https://codesandbox.io/p/sandbox/gracious-franklin-v7htwm?file=%2Fsrc%2FApp.vue%3A11%2C24](https://codesandbox.io/p/sandbox/gracious-franklin-v7htwm?file=%2Fsrc%2FApp.vue%3A11%2C24)这里简单的用`v-if`控制，切换好像没问题，或者有例子可以简单复现一下？

**Comment by Yefancy** [comment]
有办法修复吗？

**Comment by gk-shi** [comment]
@Yefancy 碰到的是图中这个错误嘛，如果是的话，晚上回去我更新一个版本修复一下
![image](https://github.com/gk-shi/v3-waterfall/assets/27017919/88cff836-026f-4358-92e7-1083ca5a64b9)

**Comment by Yefancy** [comment]
> @Yefancy 碰到的是图中这个错误嘛，如果是的话，晚上回去我更新一个版本修复一下
> 
> ![image](https://github.com/gk-shi/v3-waterfall/assets/27017919/88cff836-026f-4358-92e7-1083ca5a64b9)
> 
> 

是的。 感谢
