### ISSUE TITLE
如图，是否没有根据依次图片的高度来排布

### ISSUE THREAD

**Issue by wmhh1129** [gk-shi/v3-waterfall#32]
![image](https://github.com/gk-shi/v3-waterfall/assets/18160036/e89ac1c6-b4c8-449a-9141-d815d2b7a966)
看起来是短的条目放在了短的条目的下面，按理应该长的放短的下面 ？

**Comment by gk-shi** [comment]
排版是按整体元素高度来的，不单单算图片的。瀑布流的排版规则是：找到当前排版后的最低位置，就是下一个排版的元素位置。
就你截图上看来，1号文章和2号文章渲染完之后，1号文章的元素高度显然比2号文章高了一点，所以下个渲染的3号文章就会排在2号下了。
