### ISSUE TITLE
list动态数据有36条。但是div只渲染了部分数据。下面倒是留了div的位置。不知道为什么div数据不对

### ISSUE THREAD

**Issue by lchcy** [gk-shi/v3-waterfall#33]
![1](https://github.com/gk-shi/v3-waterfall/assets/55433643/5feab64e-edc0-4f44-a4b2-fc5491faa12c)
![2](https://github.com/gk-shi/v3-waterfall/assets/55433643/f99b4378-f0e7-4401-8eed-6e237a2684c5)

不过我缩小浏览器之后。div会增多。不知道是有什么属性来控制这个div的数量吗。不应该是list的总数量吗
麻烦帮忙看下，求求了

**Comment by lchcy** [comment]
我如果全局滚动的话，应该是不需要定最外层高度的吧

**Comment by gk-shi** [comment]
你有设置`virtualTime`字段开启虚拟列表嘛

**Comment by lchcy** [comment]
![3](https://github.com/gk-shi/v3-waterfall/assets/55433643/3542dcf3-d4ce-45c7-9fa2-b8af7ca62dd7)
就是这个样子。下面留有位置。但是并没有这些div

**Comment by lchcy** [comment]
设置了的，:virtual-time="400"

**Comment by lchcy** [comment]
我把这个属性去掉竟然可以了！！！

**Comment by gk-shi** [comment]
不加这个属性的话，相当于全部渲染了(没有虚拟列表的性能)，感觉跟你包裹`v3-waterfall`的父元素的相关css有影响，你这个项目有在线仓库嘛，如果不涉及隐私信息的话可以给我地址看看，放到 code sandbox 也行

**Comment by lchcy** [comment]
不好意思，我们的代码在devops里面。我把父元素相关的样式截图截下来了。如果方便的话麻烦看一下
![4](https://github.com/gk-shi/v3-waterfall/assets/55433643/ed8bb394-cb0b-49c1-99a3-ade958ba71e7)
![5](https://github.com/gk-shi/v3-waterfall/assets/55433643/698170c8-ee06-436f-8ad0-b746c34aa777)
![6](https://github.com/gk-shi/v3-waterfall/assets/55433643/5665aca5-5bfb-47ae-b0b9-c2fa0d06c6d4)
<img width="317" alt="7" src="https://github.com/gk-shi/v3-waterfall/assets/55433643/d4269145-cb87-47eb-b025-8ad5e8767772">

**Comment by gk-shi** [comment]
不能调试代码还真看不出来...我现在目前只能给一点思路：

**Comment by gk-shi** [comment]
不调试代码，咋一看我还真没太看出来，我只能简单给点思路了(仓库的示例`/src`里你也可以看看，我并没有指定啥特别的属性)：
1.你在`v3-waterfall`上设置的props，对照文档里看看是不是影响了，比如如果指定了`scrollBodySelector`
2.我看你最开始的第一张截图
![image](https://github.com/gk-shi/v3-waterfall/assets/27017919/6f0e0153-c25e-4215-802b-66091b782539)
这时候如果开启了`:virtual-time="400"`的情况下，页面是否有出现滚动条，如果没有，一层一层往上找找，看看是哪个元素造成没有滚动条了。
因为我看你描述在开启虚拟滚动的属性时，你缩小浏览器就能加载出来，这就类似视窗范围增大了，那么原本虚拟隐藏的元素就出现在视窗当中，自然要被加载，这么看起来逻辑也没问题...或者你能给一个问题复现的最小demo，我也可以实际调试一下

**Comment by lchcy** [comment]
你好。谢谢你提供的思路。问题解决了。是最最最外层的div有一个height:100vh。所以导致放大浏览器最外层100vh的高度小于虚拟列表计算的高度。导致加了:virtual-time="400"下面的那部分图片没有虚拟加载出来。

**Comment by gk-shi** [comment]
问题解决了就好。
如果是最外层 div 设置了高度，并且超出滚动是基于这个div时，就需要结合`scrollBodySelector`和`isMounted`属性使用了。
因为我默认是监听的整个页面滚动，这时候元素的滚动不会触发后续的事件。
