### ISSUE TITLE
 list.value = [];，这样把数组清空后怎么没有重新渲染呢？

### ISSUE THREAD

**Issue by JR-05** [gk-shi/v3-waterfall#35]

**Comment by JR-05** [comment]
掉了reRender()还是没有

**Comment by JR-05** [comment]
我觉得你可以把操作数据的动作让组件暴露相关的方法，而不是直接操作数据

**Comment by JR-05** [comment]
兄弟辛苦了

**Comment by Sunshine-Zuo** [comment]
@gk-shi 作者大大，这个问题是不是没修复完全呀，list.value = []虽然内容清空了，但是vue3-waterfall-wrapper的高度还在，导致footer的内容被顶到下面去了

**Comment by gk-shi** [comment]
> [@gk-shi](https://github.com/gk-shi) 作者大大，这个问题是不是没修复完全呀，list.value = []虽然内容清空了，但是vue3-waterfall-wrapper的高度还在，导致footer的内容被顶到下面去了

@Sunshine-Zuo 是没有重置它的高度，因为我不能确定用户是在什么时候将`list.value = []`，如果还没有全部加载完就重置了高度，还是会触发加载操作，造成一系列不可预知的问题。
如果你能确定你是加载完了全部（`isOver = true`），想清空数据，保持展示加载完成的提示，可以“曲线救国”一下：

在组件上绑定一个动态类名，`:class="{ 'reset-height': resetHeight }"`，清空时将`resetHeight.value = true`.
然后用css样式穿透修改：
```css
.reset-height ::v-deep .vue3-waterfall-wrapper {
  height: 0 !important;
}
```
