### ISSUE TITLE
使用底部 Tab 使用时，当列表已经滑动到一定位置后切换到其他Tab再回来，怎么才能保持上次列表滑动的位置呢？

### ISSUE THREAD

**Issue by JR-05** [gk-shi/v3-waterfall#37]

**Comment by gk-shi** [comment]
不好意思，出差才看到。如果要实现你这个需求的话，需要使用多个`v3-waterfall`，各自保留自己的数据，然后搭配上`keep-alive`应该就能实现了。

**Comment by JR-05** [comment]
谢谢大佬

**Comment by JR-05** [comment]
> 不好意思，出差才看到。如果要实现你这个需求的话，需要使用多个`v3-waterfall`，各自保留自己的数据，然后搭配上`keep-alive`应该就能实现了。

谢谢大佬
