### ISSUE TITLE
[Bug Report]使用了自定义高度计算函数的瀑布流元素底部出现未知间隙，预期结果不符

### ISSUE THREAD

**Issue by ylc6223** [gk-shi/v3-waterfall#39]
### 使用的版本?

^ Latest

### 最小复现demo

https://stackblitz.com/edit/vitejs-vite-rj9nhb?file=src%2FApp.vue

### 问题描述

使用了自定义高度计算函数的瀑布流元素底部出现较大的未知间隙，预期结果不符,使用开发者工具检查发现定位使用的Top值较大，不太清楚相关的计算方式
![image](https://github.com/user-attachments/assets/deb780a7-2f24-451e-aba8-76b0584b02b5)

**Comment by gk-shi** [comment]
![image](https://github.com/user-attachments/assets/c878ce92-c30b-4768-b218-409d35f534eb)
使用属性`aspect-ratio: 3 / 4`后，图片按3:4缩放，而所有图片的宽度都是元素宽度187px，所以所有图片其实都是 173*(4/3)=249.33px，有些图片原来不是3:4的展示都发生变形了，比如第一张。
![image](https://github.com/user-attachments/assets/6a61f1fb-9001-40f5-8eed-f4916281e533)
因为图片宽度是定的，所以其实每个图片的展示高度也是定的，改成红色箭头指的计算图片高度的语句展示就正常了。

红框中你原来的计算语句，计算出了按图片原比例缩放的应该的实际高度，它用在了排版上(`top`值的设定)，但是因为`aspect-ratio`的原因实际图片展示没有这个高度，就有了空隙。

这个需要你自己取舍一下。
