### ISSUE TITLE
你好，请问能不能手动触发加载更多？

### ISSUE THREAD

**Issue by akgitcom** [gk-shi/v3-waterfall#7]
你好，请问能不能手动触发加载更多

**Comment by gk-shi** [comment]
@akgitcom 你好，暂时我没有支持这个功能，但是可以曲线救国。
你自己在`v-slot:loading`中写一个手动触发的按钮，比如`加载更多`，然后不监听`@scroll-reach-bottom`事件，而改为监听你绑定在`加载更多`按钮上的点击事件。
之后请求数据往数组里面添加应该就行了。

**Comment by akgitcom** [comment]
@gk-shi 
数据添加到data.resData.album了，但是没渲染
`<v3-waterfall
            class="waterfall"
            :list="data.resData.album"
            srcKey="cover"
            :gap="12"
            :colWidth="data.styleWidth"
            :distanceToScroll="200"
            :isLoading="data.albumLoading"
            :isOver="data.albumOver"
            scrollBodySelector=".album"
            :isMounted="data.isMounted"
          >
            <template v-slot:loading>
              <div>
                <van-button type="primary" @click="getNextAlbum"
                  >加载更多</van-button
                >
              </div>
            </template>
           <template v-slot:default="slotProp">
              <div class="list-item">
                  <div class="cover-wrapper">
                    <img
                      v-if="slotProp.item.cover"
                      :src="slotProp.item.cover"
                      class="cover"
                    /></div>
              </div>
            </template>
          </v3-waterfall>`

`
const getNextAlbum = () => {
   data.resData.album.push({
    cover: "/tmp/i1.png",
    _id: "7",
  });
`

**Comment by gk-shi** [comment]
@akgitcom 
昨天因为在高铁上没有细说，刚才我自己把我的例子做了点更改实现了这个功能，代码在：[https://codesandbox.io/s/v3-waterfall-demo-u6j91?file=/src/App.vue](https://codesandbox.io/s/v3-waterfall-demo-u6j91?file=/src/App.vue)可以看到（App.vue 文件中的  `fetchList` 方法有注释以及新增的 `loadMore`方法）。
其实还是要监听 `@scrollReachBottom` 方法的。整个流程大体如下：
1.写自己的 `v-slot:loading` 元素绑定事件
2.在`@scrollReachBottom`事件中将组件的 loading 状态置为 true，这样才能加载出自己写的那个加载按钮
3.在自己按钮的点击事件中加载数据，放进渲染队列
4.在点击事件中将 loading 置为 false 隐藏按钮


因为我只能看到你这个代码片段，里面具体的问题我无法十分清楚，如果可以的话，麻烦你给我提供一下出现你上述问题的可运行代码片段或者仓库，我很乐意去发现其中的问题😊

**Comment by akgitcom** [comment]
非常感谢您在百忙之中耐心解释。
问题解决了。
谢谢

**Comment by gk-shi** [comment]
@akgitcom 没事，这是我应该做的 , 如果还发现什么问题，欢迎再跟我反馈。😁
