### ISSUE TITLE
请问之间有空白是因为什么

### ISSUE THREAD

**Issue by NightMingGit** [gk-shi/v3-waterfall#8]
![微信截图_20220504104809](https://user-images.githubusercontent.com/92633021/166617202-177c96e5-dae7-45d3-9070-09fcbb31eed6.png)

**Comment by gk-shi** [comment]
@NightMingGit 你好，还麻烦你尽量提供一下能够复现该问题的最小代码片段，可以使用 code sandbox ，或者你给个仓库地址也行。因为我周边使用了该库的同事暂时还没有出现过以上问题，我光看表现很难定位问题出在哪儿😂

**Comment by NightMingGit** [comment]
> 

https://codesandbox.io/s/hopeful-fire-ed1nm8?file=/src/App.vue

**Comment by gk-shi** [comment]
你好，问题已找到。你在 css 中：
```css
img {
  max-width: 100% !important;
}
```

这个`max-width`应该是先会以图片本身宽度来决定，如果图片本身宽度超过了容器宽度，才会以容器宽度来设置图片宽度。
而我在计算定位的时候，是一直以容器宽度为标准，然后按图片比例缩放的。
这时候就会出现案例中的空白，因为：
<img width="211" alt="image" src="https://user-images.githubusercontent.com/27017919/166623917-483f413d-d4b4-4ab9-818a-bbcc9ccf301f.png">
我在计算的时候这个图片应该是宽高 300*300 填满容器，但实际上图片是 100*100，受`max-width`的影响，它实际也只展示100*100。因此就有了 200px 的空白。

如果将`max-width`改为`width: 100%;`，该问题就没有了。

这里以后我会在考虑一下能否优化掉。

**Comment by NightMingGit** [comment]
> 你好，问题已找到。你在 css 中：
> 
> ```css
> img {
>   max-width: 100% !important;
> }
> ```
> 
> 这个`max-width`应该是先会以图片本身宽度来决定，如果图片本身宽度超过了容器宽度，才会以容器宽度来设置图片宽度。 而我在计算定位的时候，是一直以容器宽度为标准，然后按图片比例缩放的。 这时候就会出现案例中的空白，因为： <img alt="image" width="211" src="https://user-images.githubusercontent.com/27017919/166623917-483f413d-d4b4-4ab9-818a-bbcc9ccf301f.png"> 我在计算的时候这个图片应该是宽高 300_300 填满容器，但实际上图片是 100_100，受`max-width`的影响，它实际也只展示100*100。因此就有了 200px 的空白。
> 
> 如果将`max-width`改为`width: 100%;`，该问题就没有了。
> 
> 这里以后我会在考虑一下能否优化掉。

好的 麻烦了
