### ISSUE TITLE
父组件list数据更新，插槽返回的数据未更新

### ISSUE THREAD

**Issue by ovensi** [gk-shi/v3-waterfall#9]

**Comment by gk-shi** [comment]
本版本出于一些设计考虑暂不支持更新已经被渲染的数据，下个版本会考虑支持。

**Comment by zephyrJS** [comment]
请问后面能否将重新渲染的方法暴露出来

**Comment by gk-shi** [comment]
> 请问后面能否将重新渲染的方法暴露出来

@zephyrJS  后面会增加一些钩子的暴露，这个也会提供出去，最近好像找到了一个困扰好久的问题的解决方案，开始进行调整了😄

**Comment by gk-shi** [comment]
在最新版增加了模板访问原始最新数据的变量`slotProp.raw`，但只建议拿来做逻辑处理，在排版上不要使用该属性(还是因为可能会改变元素位置大小等原因)。
@zephyrJS 现在也提供了一个通过 ref 来直接调用的 `reRender` 方法主动重载。

本来想使用纯响应式方案重构一版，结果还是被一个难题卡住了，心塞，目前还是只能用这个版本😂
